sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kajal1501/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kajal1501/react-test npm test

after_success:
  docker build -t kajal1501/multi-client ./client
  docker build -t kajal1501/multi-nginx ./nginx
  docker build -t kajal1501/multi-server ./server
  docker build -t kajal1501/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to the Docker hub
  - docker push kajal1501/multi-client
  - docker push kajal1501/multi-nginx
  - docker push kajal1501/multi-server
  - docker push kajal1501/multi-worker
