sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t kajal1501/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kajal1501/react-test npm test

after_success:
  docker build -t kajal1501/multi-client ./client
  docker build -t kajal1501/multi-nginx ./nginx
  docker build -t kajal1501/multi-server ./server
  docker build -t kajal1501/multi-worker ./worker

